extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended-type-checked"
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  tsconfigRootDir: __dirname
plugins:
  - "@typescript-eslint"
rules:
  max-len: off
  require-jsdoc: off
  # linebreak-style: off
  no-shadow:
  - error
  - builtinGlobals: true
    hoist: all
    allow:
    - event
  quotes:
  - error
  - double
  - avoidEscape: true
root: true